server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    driverClassName: ${JDBC_DATABASE_DRIVER}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
jwt:
  signerKey: "hrp3kHihWpRofMCfXC8H2OYqM7SHrt3eBMG6+Rxyys0rD2F0cT6zTkAgFtW6gBU4"
token:
  accessTokenExpiryTime: 1
  refreshTokenExpiryTime: 48
